# SPDX-FileCopyrightText: 2024 CCOS-USP <https://ccos.icmc.usp.br
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: rideshare_db
    restart: always
    environment:
      POSTGRES_DB: rideshare
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:
