# SPDX-FileCopyrightText: 2024 CCOS-USP <https://ccos.icmc.usp.br
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: joynride_db

services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: joynride_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME:-joynride}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - ${DB_EXPOSED_PORT:-5432}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - joynride_network

  migrate: &basemigrate
    profiles: ['tools']
    image: migrate/migrate
    entrypoint: 'migrate -database postgresql://${DB_USER:-admin}:${DB_PASSWORD:-1234}@db:5432/${DB_DATABASE_NAME:-joynride}?sslmode=disable -path /tmp/migrations'
    command: up
    depends_on:
      - db
    volumes:
      - ./migrations:/tmp/migrations
    networks:
      - joynride_network

  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ''

volumes:
  pgdata:

networks:
  joynride_network:
    name: joynride_network
    external: true
